# Generated by Django 6.0 on 2025-12-19 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_created_at_post_date_posted_post_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='comment_media/'),
        ),
    ]
