# Generated by Django 6.0 on 2025-12-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_profile_pic_member_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterField(
            model_name='member',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
